# Generated by Django 5.0.1 on 2024-02-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_rename_issue_ticket_title_ticket_status_ticket_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='issue',
        ),
    ]
